apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 3
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: alessandervictor/nlw.service.passin:c6ca09f
        env:
        - name: SERVER_PORT
          value: "3333"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: url
        ports:
        - containerPort: 3333
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi

