version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: db-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=aloisk
      - POSTGRES_DB=passin
    volumes:
      - 'db:/bitnami/postgresql'
    networks:
      - passin

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3334:3333
    environment:
      - SERVER_PORT=3333
      - DATABASE_URL=postgresql://admin:aloisk@postgres:5432/passin
    networks:
      - passin
    depends_on:
      - postgres

networks:
  passin:
    driver: bridge
   
volumes:
  db: