name: CI

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t alessandervictor/nlw.service.passin:${{ steps.generate_sha.outputs.sha}} server-node
      
      - name: Log into the container register
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      
      - name: Push image
        run: |
          docker push alessandervictor/nlw.service.passin:${{ steps.generate_sha.outputs.sha}}
          docker tag  alessandervictor/nlw.service.passin:${{ steps.generate_sha.outputs.sha}} alessandervictor/nlw.service.passin:latest
          docker push alessandervictor/nlw.service.passin:latest